### ISSUE TITLE
Question about number of layers

### ISSUE THREAD

**Issue by LIUkhan** [SoftWiser-group/CFANE#1]
Excuse me, the default layer of the model in the paper is 2. And the Figure5(d) in the paper shows the ablation study of the number of layers from 2 layers to 10 layers. So what about the result of only one layer compared with the stacked ones? Thanks for your kind reply.

**Comment by Ph0en1xGSeek** [comment]
Hello LIU, thanks for your question.
As far as I can remember, the result of only one layer is worse than the one with two stacked layers (similar results can be found in the Appendix B of GCN paper). If you are interested in the exact number, you can modify my code and run it, it won't take your much time.
